### ISSUE TITLE
Missing docstrings on website

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#83] opened 2020-04-24 10:18 UTC
e.g. of `GreensTree.setImpedance`

**Comment by benelot** [comment] 2020-05-05 19:15
On master is no docstring for setImpedance?

**Comment by benelot** [comment] 2020-05-05 19:15
https://github.com/unibe-cns/NEAT/blob/master/neat/trees/greenstree.py

**Comment by WillemWybo** [comment] 2020-05-06 06:50
Line 271. Note that this is on the website that I build locally on my machine (on the public one all docstrings are missing)

**Comment by benelot** [comment] 2020-05-06 07:11
Hmm weird, yesterday, it had no docstring!

**Comment by benelot** [comment] 2020-05-06 07:12
Ok, weird, I will look into it.

**Comment by WillemWybo** [comment] 2020-05-06 07:18
There might be other functions with a similar name. For instance `_setImpedance()` has no docstring.

**Comment by benelot** [comment] 2020-05-07 09:16
That was probably the one I saw.

**Comment by benelot** [comment] 2020-05-07 09:44
Duplicate of #86. I will close this for now, and fix it together with #86 . Please reopen if the problem persists after fixing the other one.

**Comment by WillemWybo** [comment] 2020-05-07 09:49
Are you sure #86 and #83 they have the same cause?

**Comment by benelot** [comment] 2020-05-07 13:32
I am now sure that it does not have the same cause.

**Closed** 2020-07-17 09:22 UTC
